# Generated by Django 2.2.5 on 2019-09-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='category description')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product name')),
                ('small_image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Catalog image')),
                ('full_image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Detail image')),
                ('short_desc', models.CharField(blank=True, max_length=100, verbose_name='Short description')),
                ('full_desc', models.TextField(blank=True, verbose_name='Full description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stock quantity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
