# Generated by Django 2.2.5 on 2019-09-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190913_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='full_image',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='Detail image'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='Catalog image'),
        ),
    ]
