# Generated by Django 2.2.5 on 2019-09-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20190919_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
